version: '3.8'

services:
  code-compile:
    image: maven
    container_name: ashujavab 
    volumes:
      - "./ashudemo:/opt/javacode/"
    tty: True 

  spark-master:
    image: docker.io/bitnami/spark:3.5
    volumes:
    - ./ashudemo:/opt/javacode/
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - '8080:8080'
      - '7070:7070'