apiVersion: apps/v1 # new api version 
kind: Deployment # deployment controller 
metadata:
  creationTimestamp: null
  labels:
    app: ashudeploy1
  name: ashudeploy1 # name of deployment 
spec:
  replicas: 1 # number of pods we want 
  selector: 
    matchLabels:
      app: ashudeploy1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ashudeploy1
    spec:
      containers:
      - image: docker.io/dockerashu/ashujava:imgv2 # docker image 
        name: ashujava # name of container 
        resources: {}
status: {}
