apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ashu-web-ui
  name: ashu-lb
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ashu-web-ui
  type: LoadBalancer
status:
  loadBalancer: {}
